### ISSUE TITLE
AMSR2 Retrieval Predictor Caculation Went Wrong

### ISSUE THREAD

**Issue by XuLu-NOAA** [NOAA-EMC/GSI#678] opened 2024-01-08 20:25 UTC
When calculating the predictors for AMSR2 retrievals in clw_mod.f90 between L987 and 988, Tb obs from channels 7 and 11 are always smaller than the corresponding channels 8 and 12.  This will result in negative values inside log and fail the debug mode. The test case is on 202008250600 UTC.
Need to contact the code provider or the data provider to understand if this is a change in the data nature or a bug. @MichaelLueken 

git blame  -L 987,988 clw_mod.f90
a02fd30b src/clw_mod.f90 (Michael.Lueken 2016-08-31 17:36:25 +0000    pred_var_clw(1) = log(tb_use(7) - tb_use(8))      !(tb18v - tb18h)
a02fd30b src/clw_mod.f90 (Michael.Lueken 2016-08-31 17:36:25 +0000    pred_var_clw(2) = log(tb_use(11) - tb_use(12))    !(tb36v - tb36h)

**Comment by erinjones2** [comment] 2024-01-08 20:38
@XuLu-NOAA @MichaelLueken If I had to guess, I would say this has something to do with the (apparently unsettled) question of polarization order for channels in the AMSR2 BUFR.

**Comment by erinjones2** [comment] 2024-01-08 20:42
@XuLu-NOAA @MichaelLueken Could this have anything to do with any lingering uncertainties with the AMSR2 BUFR files?

**Comment by ADCollard** [comment] 2024-01-10 15:37
@XuLu-NOAA Can you put this in some context, please.  We do not use amsr2 operationally in GSI as the correct re-mapped bufr file needed is not available.  @emilyhcliu and @xincjin-NOAA are looking into making this work.

**Comment by TingLei-NOAA** [comment] 2024-01-19 22:32
An update:  Thanks to discussions here and off-line exchanges from  @ADCollard and @xincjin-NOAA , @XuLu-NOAA and his HAFS colleagues decided , since this data will not be used for HAFS in the foreseeable future, that it is better to add a condition test in the code and, hence, when this data is used and the issue is identified, GSI would abort with error message.  By dosing so, future developers who will use this data will know where to start a thorough investigation and give a fix.  To have a quick adding of  the above abortion with error message , after discussion between Xu and Ting,  it is decided to add it to https://github.com/NOAA-EMC/GSI/pull/681.     @XuLu-NOAA  Please have a look to see if it is as you expected.

**Comment by TingLei-NOAA** [comment] 2024-01-23 14:34
An update: after some discussions on  [PR#681,](https://github.com/NOAA-EMC/GSI/pull/681) , that fix (an exception handling by "aborting" with message" ) in that PR was removed.  The solution for this issue is, hopefully to be decided /taken by further discussion/coordination by GSI developers.

**Comment by RussTreadon-NOAA** [comment] 2024-05-07 13:07
@TingLei-NOAA and @XuLu-NOAA :  what is the status of this issue?

**Comment by TingLei-NOAA** [comment] 2024-05-07 13:31
@RussTreadon-NOAA  It could be closed while being resolved by the PR https://github.com/NOAA-EMC/GSI/pull/681. 
Thanks

**Comment by RussTreadon-NOAA** [comment] 2024-05-07 13:35
Thank you @TingLei-NOAA .  According to your suggestion, please close this issue.

**Comment by TingLei-NOAA** [comment] 2024-05-07 13:39
@RussTreadon-NOAA  I have no permission to close this issue.

**Comment by RussTreadon-NOAA** [comment] 2024-05-07 13:41
Hmm, interesting.  I'll close this issue for you.

**Closed as completed by RussTreadon-NOAA** 2024-05-07 13:41 UTC
