### ISSUE TITLE
Add more regression test cases for RRFS

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/GSI#586] opened 2023-06-22 17:27 UTC
There is only one regression test case for hybrid EnVar with conventional observations in current suite for RRFS.

We need to add more regression tests for RRFS:
1) hybrid EnVar with direct radar reflectivity analysis
2) EnKF with conventional observations 
3) EnKF with radar reflectivity observations.

We need to created the case with CONUS 13km grid.
Also, the RRFS may combine the two hybrid EnVar analyses for conventional and reflectivity observations into one. If this happens, we need to update current regression test case.

**Comment by RussTreadon-NOAA** [comment] 2023-12-07 15:10
@hu5970 , any updates on this issue?   We should add the indicated ctests or close this issue and open a new one when ctests are ready to be added.

**Comment by hu5970** [comment] 2023-12-07 16:12
We cannot decide if sdl/vdl can be used for RRFS for now. I will cehck this issue again. If we cannot, I can add test cases based on current RRFS GSI runs.

**Comment by RussTreadon-NOAA** [comment] 2023-12-07 16:17
Thank you, @hu5970.  Please update this issue once a decision is made.

**Comment by RussTreadon-NOAA** [comment] 2024-03-21 12:24
@ShunLiu-NOAA and @hu5970 :  Given that Sho's PR #700 is nearing merger into `develop`, it is time to replace or upgrade `rrfs_3denvar_glbens` with a RRFS ctest which mimics functionality in the RRFS v1 package being submitted to NCO.   We need to ensure that operational and plan operational GSI capabilities are exercised by GSI ctests.   This is why we recently updated the GSI global ctest case.  GMI assimilation is a possibility for GFS v17.  Therefore, the global ctest case was updated to include gmi data.

If possible, let's _**not**_ add several new rrfs ctests.  Ideally we have one rrfs test which includes GSI options to be exercised in RRFS v1.

**Comment by ShunLiu-NOAA** [comment] 2024-03-21 13:43
Russ, we will create a new set of test case with using regional GSI ensemble members to practice the functions used in regional DA. However, because we have to use the very different setup than the existing real time parallel to generate such a case, I will discuss with Ming about how to build this test case.

**Comment by RussTreadon-NOAA** [comment] 2024-03-21 13:49
I appreciate the challenges in creating computationally inexpensive yet representative GSI regression test cases.  To create the updated global case I had to
- covert operational fv3 tiles to low res tiles via chgres_cube
- cold start a low res  parallel using g-w
- run a few cycles to generate spun up gaussian grid backgrounds and bias correction files

This is a tedious and, sometimes, problematic undertaking.

**Comment by hu5970** [comment] 2024-03-21 15:36
Yes, we need to create low resolution case. We recent spend all our energy to run large NA 3km and CONUS cases and did not visit low resolution case for a while. I will work with Shun to try a retro run with CONUS 13km grid, which is grid for current GSI case.

**Comment by ShunLiu-NOAA** [comment] 2024-03-21 18:12
Russ, 
Thank you for providing this information.
As Ming mentioned, we will revisit 13km resolution test case.

Shun

**Comment by RussTreadon-NOAA** [comment] 2024-05-07 13:11
@ShunLiu-NOAA and @hu5970 :  what is the status of this issue?

**Comment by hu5970** [comment] 2024-05-07 14:44
I can run CONUS 13 km RRFS case on both Hera now. I need to find a time to create cases for RRFS based on this issue.

**Comment by RussTreadon-NOAA** [comment] 2024-05-07 14:45
Thank you @hu5970 for the update.  Hera is down today (5/7) for PM.

**Closed as completed** 2024-06-27 12:11 UTC
