### ISSUE TITLE
update on current GSI regression tests 

### ISSUE THREAD

**Issue by TingLei-daprediction** [NOAA-EMC/GSI#513] opened 2022-12-15 19:17 UTC
As discussed with @RussTreadon-NOAA  before, to open this issue is to initiate discussion/information  on how to do current GSI regression tests .
An existing wiki page is https://github.com/NOAA-EMC/GSI/wiki/GSI-Ctests-(regression-tests), which could be updated with helps from information provided in this issue. 
Now, the current regression tests could only be done hera. 
In hera, 
1) when you run " build.sh " to build gsi, make sure "
REGRESSION_TESTS=TRUE.
2) please note, the currrent regression tests are built with 
ENKF_MODE=${ENKF_MODE:-"GFS"}  
So, if you are using other options, please pay attention to do modifications if needed. 
3) after building,  you could just enter into build directory and run tests as standard practice. 
The only change I noticed is that you need to edit regression_var.sh,
for line 
^^
export local_or_default="${local_or_default:-/scratch1/NCEPDEV/da/$LOGNAME}"
VV
if you are not in da group, you either need to define local_or_default or change the "da" dir to directory you have permission to. 
That is what the developers need to know to run regression tests.  For deep understanding and how to create their own regression tests, more discussion/information would be helpful.  Tracing in the build.sh and cmake files would help. 
Any comments/corrections are welcome .

**Comment by hongli-wang** [comment] 2022-12-16 21:29
Hi Ting, 

Thanks for sharing this.  

I don't have any experience on this, and need more guidance on the tests. I saw there is a driver: regression_driver.sh, but it needs input parameters.  Is this the driver script I should run? If yes, how to specify the input parameters. 

FYI. I don't find the variable local_or_default in my shell script. You can find my GSI dir on Hera: 
/scratch1/BMC/wrfruc/hwang/smoke/test_gsi_for_merge/GSI/regression

Thanks, 
Hongli

**Comment by TingLei-daprediction** [comment] 2022-12-16 21:39
@hongli-wang  now, that driver script is invoked by ctest. 
you can just start to run tests like " ctest -j8 "   (using 8 "processes" to run tasks).  
I will finish a couple of fv3-lam tests for your PR as soon as possible.

**Comment by hu5970** [comment] 2023-01-06 06:08
Remove regression tests: arw_binary,arw_netcdf,nmm_binary,nmm_netcdf,nmmb_nems_4denvar
    Add regression case for RRFS: rrfs_3denvar_glbens

**Comment by RussTreadon-NOAA** [comment] 2023-01-23 22:08
@TingLei-daprediction , may this issue be closed?

**Comment by TingLei-daprediction** [comment] 2023-01-23 22:49
@RussTreadon-NOAA   If you think the information gathered/ documented on this issue has been enough for an documentation on current GSI regression tests and the GSI wiki on this could be updated , this issue could be closed. 
Thanks.

**Comment by RussTreadon-NOAA** [comment] 2023-01-23 23:36
@TingLei-daprediction , since you opened the issue you may also close it.   Thanks.

**Comment by TingLei-NOAA** [comment] 2023-01-24 14:04
A recently updated GSI wiki on the  current GSI regression tests using ctest could be found at https://github.com/NOAA-EMC/GSI/wiki/GSI-Ctests-(regression-tests).   This issue will be closed.

**Closed as completed** 2023-01-24 14:05 UTC
