### ISSUE TITLE
update the regression test checks

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/GSI#647] opened 2023-10-25 15:35 UTC
Some of the regression test checks need to be updated or removed to better reflect the results of the regression tests.
such as  maxmem and timing scalability tests.

Need to check and revise the following two files:

regression/regression_test.sh
regression/regression_test_enkf.sh

**Comment by RussTreadon-NOAA** [comment] 2023-10-25 17:36
As [reported](https://github.com/NOAA-EMC/GSI/pull/646#issuecomment-1779748265) in GSI PR #645, remove the maxmem and timing scalability tests from `regression_test.sh` and `regression_test_enkf.sh`.   Rerun the seven ctests on Hera.  All tests passed.
```
Hera(hfe03):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr645/build$ ctest -j 7
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr645/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 7: global_enkf
    Start 4: netcdf_fv3_regional
    Start 3: rrfs_3denvar_glbens
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
1/7 Test #4: netcdf_fv3_regional ..............   Passed  491.83 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  675.13 sec
3/7 Test #7: global_enkf ......................   Passed  949.82 sec
4/7 Test #6: hafs_3denvar_hybens ..............   Passed  2182.70 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  2308.16 sec
6/7 Test #2: rtma .............................   Passed  2474.11 sec
7/7 Test #1: global_4denvar ...................   Passed  3053.83 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 3053.84 sec
```
This is an expected result since PR #645 does not alter code, namelists, modules, or scripts.

**Comment by hu5970** [comment] 2023-10-25 17:42
Should we also remove the data, namelist, and scripts of the old cases that have been removed? 
If so, we should create a special PR for this cleaning.

**Comment by RussTreadon-NOAA** [comment] 2023-10-25 17:48
Yes, removed ctests should have everything related to them removed.   I did so in my Hera working copy of `hafs-community:feature/hafs_rtcases`.   Feel free to look at what's been done in `/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr645`.   We could expand the scope of PR #645 to include changes from this issue since PR #645 and this issue both involve regression test changes.  

Once changes to remove old tests are merged into `develop`, I will remove the staged data for these tests from various machines.

**Comment by hu5970** [comment] 2023-10-25 17:57
Agree. Should we ask Jing to merge your Hera working copy: /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr645 to her PR 645?

**Closed as completed** 2023-10-27 12:24 UTC
