### ISSUE TITLE
OU MAP lab developments of convective-scale static background error covariance within GSI for FV3-LAM

### ISSUE THREAD

**Issue by YueYang-OU** [NOAA-EMC/GSI#572] opened 2023-05-10 14:24 UTC
A convective-scale static background error covariance (**B**) is developed by OU MAP lab for direct assimilation of radar reflectivity within GSI-based hybrid EnVar system (Wang and Wang 2021, MWR). Such static **B** is further developed for FV3-LAM by OU MAP lab (Yang et al., 2023).
 
The developments include,
(1) extension of control variables (CVs) to include hydrometeors, vertical velocity, and reflectivity.
(2) Utilization of (u, v) and rh as the optimal momentum and humidity CVs.
(3) reflectivity-dependent binning method for static covariance statistics.
(4) adaptive incorporation of static **B** in hybrid EnVar system based on the quality of ensemble covariances.
(5) extension of balance operator to include cross-variable correlations that are suitable for convective scales.

**Comment by ShunLiu-NOAA** [comment] 2023-05-18 15:03
@TingLei-NOAA @shoyokota @chunhuazhou Let me know if you are available to review this PR. Thank you.

**Comment by TingLei-daprediction** [comment] 2023-05-18 16:13
@ShunLiu-NOAA  Thanks for asking.  However, before we go to PR steps, please allow me share a few thoughts on this development.  One key of this set of developments is the "balance relationship/regression relationship" built for some variables in the convective scale application.  That is a very interesting work to address the finding and constructing such "balance"  in the convective scale data assimilation.  I think the impacts of this method with its' currently calculated balance relationship needs more tests before it is put into EMC GSI repository.  This PR gives a good chance for scientist who is interested in this development to use and evaluate this development, which would help attain a better understanding of this development's benefit and limitations before any decision be made on if it needs to be add in the EMC GSI repository.

**Comment by shoyokota** [comment] 2023-05-19 15:18
@ShunLiu-NOAA Sorry, this unassignment is my mistake. Could you add me again?

I'm very interested in this PR. It probably takes time since I am not necessarily familiar with the static B coding in GSI, but I'd like to learn it. I agree with Ting's opinion, but I think merging this PR as one option is beneficial and less disadvantage. It may be another good option to test it in more detail after this PR is merged.

**Comment by ShunLiu-NOAA** [comment] 2023-05-19 17:10
Sho, I add you as a reviewer in https://github.com/NOAA-EMC/GSI/pull/576

**Closed as completed** 2024-05-07 13:14 UTC
