### ISSUE TITLE
fix the issue of reading NEXRAD bufr file

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [NOAA-EMC/GSI#81] opened 2020-11-06 14:26 UTC
FV3LAMDA sometimes can't read NEXRAD bufr files due to checking subset status before reading data. This checking step is not necessary and should be turned off.

Before the fix:
For today's 12z LAMDA:

regional_gsianl_tm01_12.log: RADAR_BUFR_READ_ALL:  problem opening level 2 bufr file "l2rwbufr"
regional_gsianl_tm02_12.log: RADAR_BUFR_READ_ALL:  problem opening level 2 bufr file "l2rwbufr"
regional_gsianl_tm03_12.log: RADAR_BUFR_READ_ALL:  problem opening level 2 bufr file "l2rwbufr"
regional_gsianl_tm04_12.log: RADAR_BUFR_READ_ALL:  problem opening level 2 bufr file "l2rwbufr"
regional_gsianl_tm05_12.log: RADAR_BUFR_READ_ALL:  problem opening level 2 bufr file "l2rwbufr"

File sizes for the 12z NAM nexrad file:

-rw-rw-r-- 1 nwprod prod 1218249536 Oct 21 13:15 nam.t12z.nexrad.tm00.bufr_d
-rw-rw-r-- 1 nwprod prod  829225392 Oct 21 12:18 nam.t12z.nexrad.tm01.bufr_d
-rw-rw-r-- 1 nwprod prod  951898336 Oct 21 11:23 nam.t12z.nexrad.tm02.bufr_d
-rw-rw-r-- 1 nwprod prod  951984000 Oct 21 10:30 nam.t12z.nexrad.tm03.bufr_d
-rw-rw-r-- 1 nwprod prod 1030995288 Oct 21 10:00 nam.t12z.nexrad.tm04.bufr_d
-rw-rw-r-- 1 nwprod prod 1072084336 Oct 21 10:00 nam.t12z.nexrad.tm05.bufr_d
-rw-rw-r-- 1 nwprod prod 1235644904 Oct 21 09:40 nam.t12z.nexrad.tm06.bufr_d

Conclusion: The smaller NAM nexrad files are the ones the code has problems reading. I recall seeing this before but this is the first time I was able to quantify it. It makes sense that the RAP files are giving the same error since they are always much  smaller than the NAM ones due to the early data cutoff.

after the bug fix, gsi can read NEXRAD bufr files from both RAP and NAM dump:

[Shun.Liu@m110a2 log]$ grep RADAR_BUFR *12*.log | grep num_radar
regional_gsianl_firstguess_tm06_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =          107
regional_gsianl_tm00_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =           78
regional_gsianl_tm01_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =           92
regional_gsianl_tm02_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =           91
regional_gsianl_tm03_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =           93
regional_gsianl_tm04_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =           98
regional_gsianl_tm05_12.log: RADAR_BUFR_READ_ALL:  num_radars_0 =          107

  regional_gsianl_tm**_12.log .0 is from NAM dump. 
[Shun.Liu@m110a2 log]$ grep RADAR_BUFR *12*.log.0 | grep num_radar
regional_gsianl_firstguess_tm06_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =          106
regional_gsianl_tm00_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =           86
regional_gsianl_tm01_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =           92
regional_gsianl_tm02_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =           95
regional_gsianl_tm03_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =          106
regional_gsianl_tm04_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =          107
regional_gsianl_tm05_12.log.0: RADAR_BUFR_READ_ALL:  num_radars_0 =          109

**Comment by ShunLiu-NOAA** [comment] 2020-11-06 15:01
Mike,

I already create an issue (#81) and pull request (#82). Is it correct? What
should I do in the next step?
Thanks.

Shun

**Comment by MichaelLueken-NOAA** [comment] 2020-11-06 15:12
Hi Shun,

The issue is fine.  For the pull request, please see:

https://github.com/NOAA-EMC/GSI/wiki/GSI-GitHub-General-User-Information#preparing-a-pull-request-pr

The contents of the pull request look fine to me, but there should only be a single commit.  Please squash merge your fork's rw_read branch into your fork's master, then create the pull request using your fork's master.

If you have any questions, please let me know.

Mike

**Comment by ShunLiu-NOAA** [comment] 2020-11-06 15:31
Mike,

Thank you for your help. I did follow the step. However, I made two commits
to rw_read branch and merge re_read to fork.master twice. How can I fix
this and make all these in a single commit?

Shun

**Comment by MichaelLueken-NOAA** [comment] 2020-11-06 16:48
Hi Shun,

I'm not sure 100% if this will work, but here are the steps to remove the October 23 update to master and only have a single commit from your rw_read branch:

```

1. git clone --recursive git@github.com:ShunLiu-NOAA/GSI.git update
2. cd update
3. git checkout 4d23c05279d3ec31119d9538fbbee38a2ba2837c
4. git checkout -b master-temp
5. git branch -D master
6. git checkout -b master
7. git remote add upstream git@github.com:NOAA-EMC/GSI.git
8. git remote update
9. git merge upstream/master
10. git checkout rw_read
11. git checkout master
12. git merge --squash rw_read
13. git commit -m "GitHub Issue NOAA-EMC/GSI#81. Fix the issue of reading NEXRAD bufr file."
14. git branch -D master-temp
15. git push origin master --force

```

Basically, these steps will checkout a copy of your master at the revision before c037c3c was committed, create a temporary copy of master at this point, delete current master, recreate master from the temporary master, merge the latest changes to master back in, then finally merging the update from rw_read back in.  This will leave you with a version of master with a single commit, which you should be able to create the pull request from.

Please let me know if you encounter issues.

Mike

**Comment by ShunLiu-NOAA** [comment] 2020-11-06 17:03
Mike,

I am following your instruction. in step 3, I the message:

[Shun.Liu@m110a3 update]$ git checkout
4d23c05279d3ec31119d9538fbbee38a2ba2837c
Note: checking out '4d23c05279d3ec31119d9538fbbee38a2ba2837c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 4d23c05... Merge pull request #40 from TingLei-NOAA/master

Is it correct?

Shun

**Comment by MichaelLueken-NOAA** [comment] 2020-11-06 17:09
Hi Shun,

Yes, that is correct.  Step 4 is the git checkout -b master-temp, which will move you out of detached HEAD state.

Mike

**Closed** 2020-11-13 17:28 UTC
