### ISSUE TITLE
Verification of readin_localizaiion=.true. for regional GSI

### ISSUE THREAD

**Issue by TingLei-daprediction** [NOAA-EMC/GSI#388] opened 2022-05-20 19:17 UTC
One recent test of FV3-LAM GSI compiled with debug mode  using readin_localization=.true. shows error message about index exceeding the upper boundary in convert_km_to_grid_units (hybrid_ensemble_isotropic.F90) at the labelled line as shown below:
if(nz>1)then
do n=2,n_ens
nk=(n-1)*grd_loc%nsig
do k=1,grd_loc%nsig
s_ens_h_gu_x(nk+k)=s_ens_h_gu_x(k) !clt runtime error occured,
s_ens_h_gu_y(nk+k)=s_ens_h_gu_y(k)
enddo
enddo
endif
Further investigation let me suspect the assginments of s_ens_h_gu_x are not correctly done when a map should be done between (1:nsig) and (grd_loc%kbegin_loc:grd_loc%kend_alloc). 
readin_localization is not used in EMC's regional runs, but the vertically varied horizontal scale is regarded as beneficial as done in the global GSI. Hence, this issue is expected to invite comments/suggestions and document progress on this point

**Comment by TingLei-daprediction** [comment] 2022-05-25 14:47
An update:  it is verified that the rationale behind mapping between s_ens_h_gu_x(y) and the read-in vertically s_ens_hv is right ( from fields of nsig to fields of nsig*n_ens). But a simple fix is needed for subroutine convert_km_to_grid_units(s_ens_h_gu_x,s_ens_h_gu_y,nz) in hybrid_ensemble_isotropic.F90

^^
 real(r_kind),intent(  out) ::s_ens_h_gu_x(nz),s_ens_h_gu_y(nz)
V 
Should be
^^
real(r_kind),intent(  out) ::s_ens_h_gu_x(nzXn_ens),s_ens_h_gu_y(nzXn_ens)
V
It seems regional GSI without compiled debug mode  could run without abortion. maybe it could still get correct results if the array in the memory is stored continuously .
@MichaelLueken-NOAA  would you please take care of this fix after you review and confirm my conclusion?   My master branches in my fork have other changes in a PR or other changes to be taken care in the future.

**Comment by MichaelLueken** [comment] 2022-05-25 15:12
@TingLei-daprediction No, you will need to create a new branch and create a PR from the branch.  To create the new branch and apply the necessary fix, in your local cloned copy:

1) git remote add upstream https://github.com/NOAA-EMC/GSI.git
2) git remote update
3) git checkout upstream/develop
4) git submodule update
5) git checkout -b feature/verification_388 (or whatever you would like the branch to be called)

From this point, please make the required change, add the change (git add hybrid_ensemble_isotropic.F90), and then commit (`git commit -m "GitHub Issue NOAA-EMC/GSI#388.  Verification of readin_localization=.true. for regional GSI."`).  Please create the PR from this branch.

It is important to note that there are no FV3-LAM regression tests, so it is impossible to test and approve the change myself.  So, please move forward with the above steps so that this fix can be merged to the authoritative develop branch.

**Comment by TingLei-NOAA** [comment] 2022-05-25 15:16
@MichaelLueken-NOAA  the problem is how I , in my fork, can get a clean version from EMC master without going through my master/develop in my forks?  Following the regular steps as you listed above, the checkedout local branch would contain those changes in my master which should not be for this fix.   Any ways to avoid this ?  Thanks.

**Comment by TingLei-NOAA** [comment] 2022-05-25 15:17
@MichaelLueken-NOAA  Thanks. I will try your instructions and let you know how it works.

**Comment by TingLei-NOAA** [comment] 2022-05-25 15:19
And I will do a comparison between the new and old codes compiled in non-debug mode.

**Comment by TingLei-daprediction** [comment] 2022-05-26 14:59
The quick fix is in the PR 388. It is confirmed in the test case that the previous exceeding bounds error in the regional gsi debug mode would not affect the correctness of the results when GSI is built with optimization. It is explained by assuming the involved array is stored continuously in the memory and hence, it only represent a safety issue with potentially risk to affect the results.

**Comment by MichaelLueken** [comment] 2022-05-26 15:21
@TingLei-daprediction These changes haven't been merged to the authoritative repository, so I will reopen this issue and it will be closed when PR #396 has been merged to the authoritative repository.

**Comment by TingLei-NOAA** [comment] 2022-05-26 15:22
Mike,
Got it! Thanks a lot for your help!
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Closed as completed** 2022-06-01 17:06 UTC

**Comment by TingLei-NOAA** [comment] 2022-06-01 17:15
Mike,
Thank you!
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624
