### ISSUE TITLE
Mesonet over land q obs removed from regional sfc DA

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [NOAA-EMC/GSI#701] opened 2024-02-16 20:55 UTC
Recent PR #[675](https://github.com/NOAA-EMC/GSI/pull/675#issuecomment-1946697000) removed obs type 188 (mesonet over land) from the landsfctype flag in setupt.f90 and setupq.f90. Obs type 188 was also removed from the calculation of the global_2m_land flag in readprepbufr.f90. 

In setupq.f90, the landsurfacetype variable is then used to turn on l_pbl_pseudo_itype, if l_pbl_pseudo_surfobsq is true. Removal of obs type 188 will change the results for  l_pbl_pseudo_surfobsq = .true. , which (I assume) is the option used in the regional sfc DA. 

In setupt and readprepbufr, the removal of obstype 188 only affects the global assimilation of 2m obs. I have a vague memory that I removed the mesonet obs for the global DA intentionally, so I want to go back and check that. As an interim solution, I propose that I revert the calculation of l_pbl_pseudo_surfobsq in setupq to include 188, while I look into the global case.

**Comment by ClaraDraper-NOAA** [comment] 2024-02-16 20:56
@hu5970 Please add any details I missed (or let me know if you'd rather establish your own issue). Also, are there any tests that we can do to make sure I've fixed it?

**Comment by hu5970** [comment] 2024-02-16 21:31
@ClaraDraper-NOAA Thanks for made this issue to check the impact of removing 188. I am running some RRFS tests with the new GSI code to check the impact of the latest code (including remove 188) in RRFS. I do not think we need another issue for this. Thanks, Ming

**Comment by ClaraDraper-NOAA** [comment] 2024-02-16 22:07
Thanks Ming! 

I think I've figured out what happened, and if i'm right there may be a small change in your results, but if anything it'll be an improvement (more obs included).

Looking at my commit on [Jun 5, 2023](https://github.com/NOAA-EMC/GSI/commit/57ddc31054e79c8b12e748e5407c43c15d5ffe1f#diff-0f559cd6512f9e3c37211cc94630633cd3ab5baf78287413ab953382bd85a154)

* I introduce landsfctype (line 290)
* Line 379, I calculate landsfctype with 188 included 
 landsfctype =( itype==181 .or. itype==183 .or. itype==187 .or. itype==188  )

This is used inside the loop over the obs that spans lines 376 to 411. In this loop landsfctype is only used in the global case (hofx_2m_sfcfile = .true.).

* Then there is a second loop over the obs, starting line 460. 
In this loop, I replace the original code (starting line 467): 

     ! Flag static conditions to create PBL_pseudo_surfobsq obs.
     l_pbl_pseudo_itype = l_pbl_pseudo_surfobsq .and.         &
                          ( itype==181 .or. itype==183 .or.itype==187 )

with 

   landsfctype =( itype==181 .or. itype==183 .or. itype==187 )
   l_pbl_pseudo_itype = l_pbl_pseudo_surfobsq .and. landsfctype

So, the 188 obstype was never used for the l_pbl_pseudo_surfobsq case. 

Then,  in my most recent PR I remove 188 from the landsfctype flag in the first loop. The first loop is an obs filtering loop, so it may affect your results if the inclusion of 188 changes the obs that are kept. However,  188 was never being included in the second loop. 

I also checked the history between my two PRs, and didn't see any relevant changes.

**Comment by ClaraDraper-NOAA** [comment] 2024-02-16 22:42
FYI: I also went back over my notes, and my not having added mesonet obs was intentional (lower quality, generally in areas where we already have obs). Do you think I should re-visit this decision, and look at adding them in for the global DA?

**Comment by hu5970** [comment] 2024-02-20 18:38
@ClaraDraper-NOAA 
I run several cases and confirmed that your change to remove the 188 does not impact RRFS analysis. The 188 should not be used for the "l_pbl_pseudo_surfobsq" because of its poor quality and high density. 
Thanks for checking this and sorry for false alarm on the impact to the RRFS. 

Ming

**Comment by ClaraDraper-NOAA** [comment] 2024-02-20 18:46
@hu5970 Ming - Glad it worked out! Thanks for the update.

**Comment by ClaraDraper-NOAA** [comment] 2024-02-22 23:06
@hu5970 @RussTreadon-NOAA  Can i close this issue?

**Comment by RussTreadon-NOAA** [comment] 2024-02-23 00:04
Thanks for asking @ClaraDraper-NOAA .  I agree.  We can probably close this issue since we now have issue #701.  That said, let's wait for @hu5970 's feedback.

**Comment by hu5970** [comment] 2024-02-23 06:48
Agree to close this issue. Thanks, Ming

**Closed as completed** 2024-05-07 13:01 UTC
